<?php

use Illuminate\Database\Seeder;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;
use App\Currency;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            // [name, code, numeric_code, nbp_table, forex, nbp]
            ["UAE Dirham","AED","784","B",true,true],
            ["Afghani","AFN","971","B",false,true],
            ["Lek","ALL","008","B",true,true],
            ["Armenian Dram","AMD","051","B",false,true],
            ["Netherlands Antillean Guilder","ANG","532","B",true,true],
            ["Kwanza","AOA","973","B",false,true],
            ["Argentine Peso","ARS","032","B",true,true],
            ["Australian Dollar","AUD","036","A",true,true],
            ["Aruban Florin","AWG","533","B",true,true],
            ["Azerbaijan Manat","AZN","944","B",false,true],
            ["Convertible Mark","BAM","977","B",false,true],
            ["Barbados Dollar","BBD","052","B",true,true],
            ["Taka","BDT","050","B",true,true],
            ["Bulgarian Lev","BGN","975","A",true,true],
            ["Bahraini Dinar","BHD","048","B",true,true],
            ["Burundi Franc","BIF","108","B",true,true],
            ["Bermudian Dollar","BMD","060","",true,false],
            ["Brunei Dollar","BND","096","B",true,true],
            ["Boliviano","BOB","068","B",true,true],
            ["Mvdol","BOV","984","",false,false],
            ["Brazilian Real","BRL","986","A",true,true],
            ["Bahamian Dollar","BSD","044","B",true,true],
            ["Ngultrum","BTN","064","",false,false],
            ["Pula","BWP","072","B",true,true],
            ["Belarusian Ruble","BYN","933","B",false,true],
            ["Belize Dollar","BZD","084","B",true,true],
            ["Canadian Dollar","CAD","124","A",true,true],
            ["Congolese Franc","CDF","976","B",true,true],
            ["WIR Euro","CHE","947","",false,false],
            ["Swiss Franc","CHF","756","A",true,true],
            ["WIR Franc","CHW","948","",false,false],
            ["Unidad de Fomento","CLF","990","",false,false],
            ["Chilean Peso","CLP","152","A",true,true],
            ["Yuan Renminbi","CNY","156","A",true,true],
            ["Colombian Peso","COP","170","B",true,true],
            ["Unidad de Valor Real","COU","970","",false,false],
            ["Costa Rican Colon","CRC","188","B",true,true],
            ["Peso Convertible","CUC","931","",false,false],
            ["Cuban Peso","CUP","192","B",true,true],
            ["Cabo Verde Escudo","CVE","132","B",true,true],
            ["","CYP","","",true,false],
            ["Czech Koruna","CZK","203","A",true,true],
            ["Djibouti Franc","DJF","262","B",true,true],
            ["Danish Krone","DKK","208","A",true,true],
            ["Dominican Peso","DOP","214","B",true,true],
            ["Algerian Dinar","DZD","012","B",true,true],
            ["Egyptian Pound","EGP","818","B",true,true],
            ["Nakfa","ERN","232","B",false,true],
            ["Ethiopian Birr","ETB","230","B",true,true],
            ["Euro","EUR","978","A",true,true],
            ["Fiji Dollar","FJD","242","B",true,true],
            ["Falkland Islands Pound","FKP","238","",false,false],
            ["Pound Sterling","GBP","826","A",true,true],
            ["Lari","GEL","981","B",false,true],
            ["Ghana Cedi","GHS","936","B",false,true],
            ["Gibraltar Pound","GIP","292","B",false,true],
            ["Dalasi","GMD","270","B",true,true],
            ["Guinean Franc","GNF","324","B",true,true],
            ["Quetzal","GTQ","320","B",true,true],
            ["Guyana Dollar","GYD","328","B",false,true],
            ["Hong Kong Dollar","HKD","344","A",true,true],
            ["Lempira","HNL","340","B",true,true],
            ["Kuna","HRK","191","A",true,true],
            ["Gourde","HTG","332","B",true,true],
            ["Forint","HUF","348","A",true,true],
            ["Rupiah","IDR","360","A",true,true],
            ["New Israeli Sheqel","ILS","376","A",true,true],
            ["Indian Rupee","INR","356","A",true,true],
            ["Iraqi Dinar","IQD","368","B",true,true],
            ["Iranian Rial","IRR","364","B",true,true],
            ["Iceland Krona","ISK","352","A",true,true],
            ["Jamaican Dollar","JMD","388","B",true,true],
            ["Jordanian Dinar","JOD","400","B",true,true],
            ["Yen","JPY","392","A",true,true],
            ["Kenyan Shilling","KES","404","B",true,true],
            ["Som","KGS","417","B",false,true],
            ["Riel","KHR","116","B",true,true],
            ["Comorian Franc ","KMF","174","B",true,true],
            ["North Korean Won","KPW","408","",false,false],
            ["Won","KRW","410","A",true,true],
            ["Kuwaiti Dinar","KWD","414","B",true,true],
            ["Cayman Islands Dollar","KYD","136","",true,false],
            ["Tenge","KZT","398","B",true,true],
            ["Lao Kip","LAK","418","B",true,true],
            ["Lebanese Pound","LBP","422","B",true,true],
            ["Sri Lanka Rupee","LKR","144","B",true,true],
            ["Liberian Dollar","LRD","430","B",true,true],
            ["Loti","LSL","426","B",true,true],
            ["", "LTL", "", "", true,false],
            ["", "LVL", "", "", true,false],
            ["Libyan Dinar","LYD","434","B",true,true],
            ["Moroccan Dirham","MAD","504","B",true,true],
            ["Moldovan Leu","MDL","498","B",true,true],
            ["Malagasy Ariary","MGA","969","B",true,true],
            ["Denar","MKD","807","B",true,true],
            ["Kyat","MMK","104","B",true,true],
            ["Tugrik","MNT","496","B",true,true],
            ["Pataca","MOP","446","B",true,true],
            ["Ouguiya","MRU","929","B",false,true],
            ["Mauritius Rupee","MUR","480","B",true,true],
            ["Rufiyaa","MVR","462","B",true,true],
            ["Malawi Kwacha","MWK","454","B",true,true],
            ["Mexican Peso","MXN","484","A",true,true],
            ["Mexican Unidad de Inversion (UDI)","MXV","979","",false,false],
            ["Malaysian Ringgit","MYR","458","A",true,true],
            ["Mozambique Metical","MZN","943","B",false,true],
            ["Namibia Dollar","NAD","516","B",true,true],
            ["Naira","NGN","566","B",true,true],
            ["Cordoba Oro","NIO","558","B",true,true],
            ["Norwegian Krone","NOK","578","A",true,true],
            ["Nepalese Rupee","NPR","524","B",true,true],
            ["New Zealand Dollar","NZD","554","A",true,true],
            ["Rial Omani","OMR","512","B",true,true],
            ["Balboa","PAB","590","B",true,true],
            ["Sol","PEN","604","B",true,true],
            ["Kina","PGK","598","B",true,true],
            ["Philippine Peso","PHP","608","A",true,true],
            ["Pakistan Rupee","PKR","586","B",true,true],
            ["Zloty","PLN","985","",true,true],
            ["Guarani","PYG","600","B",true,true],
            ["Qatari Rial","QAR","634","B",true,true],
            ["Romanian Leu","RON","946","A",true,true],
            ["Serbian Dinar","RSD","941","B",true,true],
            ["Russian Ruble","RUB","643","A",true,true],
            ["Rwanda Franc","RWF","646","B",true,true],
            ["Saudi Riyal","SAR","682","B",true,true],
            ["Solomon Islands Dollar","SBD","090","B",true,true],
            ["Seychelles Rupee","SCR","690","B",true,true],
            ["Sudanese Pound","SDG","938","B",true,true],
            ["Swedish Krona","SEK","752","A",true,true],
            ["Singapore Dollar","SGD","702","A",true,true],
            ["","SIT","","",true,false],
            ["Saint Helena Pound","SHP","654","",false,false],
            ["Leone","SLL","694","B",true,true],
            ["Somali Shilling","SOS","706","B",true,true],
            ["Surinam Dollar","SRD","968","B",false,true],
            ["South Sudanese Pound","SSP","728","B",false,true],
            ["","STD","","",true,false],
            ["Dobra","STN","930","B",false,true],
            ["El Salvador Colon","SVC","222","B",true,true],
            ["Syrian Pound","SYP","760","B",true,true],
            ["Lilangeni","SZL","748","B",true,true],
            ["Baht","THB","764","A",true,true],
            ["Somoni","TJS","972","B",false,true],
            ["Turkmenistan New Manat","TMT","934","B",false,true],
            ["Tunisian Dinar","TND","788","B",true,true],
            ["Pa’anga","TOP","776","B",false,true],
            ["Turkish Lira","TRY","949","A",true,true],
            ["Trinidad and Tobago Dollar","TTD","780","B",true,true],
            ["New Taiwan Dollar","TWD","901","B",true,true],
            ["Tanzanian Shilling","TZS","834","B",true,true],
            ["Hryvnia","UAH","980","A",true,true],
            ["Uganda Shilling","UGX","800","B",true,true],
            ["US Dollar","USD","840","A",true,true],
            ["Peso Uruguayo","UYU","858","B",true,true],
            ["Unidad Previsional","UYW","927","",false,false],
            ["Uzbekistan Sum","UZS","860","B",true,true],
            ["Bolívar Soberano","VES","928","B",false,true],
            ["Dong","VND","704","B",true,true],
            ["Vatu","VUV","548","B",true,true],
            ["Tala","WST","882","B",true,true],
            ["CFA Franc BEAC","XAF","950","B",true,true],
            ["East Caribbean Dollar","XCD","951","B",false,true],
            ["SDR (Special Drawing Right)","XDR","960","A",false,true],
            ["CFA Franc BCEAO","XOF","952","B",true,true],
            ["CFP Franc","XPF","953","B",true,true],
            ["Yemeni Rial","YER","886","B",true,true],
            ["Rand","ZAR","710","A",true,true],
            ["","ZMK","","",true,false],
            ["Zambian Kwacha","ZMW","967","B",false,true],
            ["Zimbabwe Dollar","ZWL","932","B",false,true],
        ];

        $output = new ConsoleOutput();
        $progressBar = new ProgressBar($output, count($currencies));
        $progressBar->start();

        foreach($currencies as $currency) {
            $newCurrency = new Currency();
            $newCurrency->name = $currency[0];
            $newCurrency->code = $currency[1];
            $newCurrency->numeric_code = $currency[2];
            $newCurrency->nbp = $currency[5];
            $newCurrency->nbp_table = $currency[3];
            $newCurrency->forex = $currency[4];
            $newCurrency->save();
            $progressBar->advance();
        }

        $progressBar->finish();
        echo PHP_EOL;
    }
}
